from enum import Enum


class VenueCapability(str, Enum):
    QUOTE = "QUOTE"
    ROUTING = "ROUTING"
    TRANSACTION_BUILDING = "TRANSACTION_BUILDING"
    SIMULATION = "SIMULATION"
    EXECUTION = "EXECUTION"
    REPLAY = "REPLAY"
    PORTFOLIO_FEEDBACK = "PORTFOLIO_FEEDBACK"
    MARKET_RESOLUTION = "MARKET_RESOLUTION"
    MULTI_HOP = "MULTI_HOP"
    PARTIAL_FILL = "PARTIAL_FILL"
    SLIPPAGE_MODEL = "SLIPPAGE_MODEL"
